### ISSUE TITLE
Publish Apollo Router plugin crate

### ISSUE THREAD

**Issue by rcrowe** [graphql-hive/console#291]
Would you be up for publishing the plugin to https://crates.io?

This would allow us to build a custom Apollo Router with a number of custom plugins beyond just the Hive one.

**Comment by kamilkisiela** [comment]
Definitely, it's just that Apollo Router is not published as a crate and has no versioning, so it's going to be tricky to maintain yours and GraphQL Hive crates.

**Comment by pfyod** [comment]
https://crates.io/crates/apollo-router

**Comment by akoenig** [comment]
@kamilkisiela, I have a question that may deviate slightly from the current issue. I would like to know your thoughts on implementing a proper versioning schema for the Apollo Router (Hive Edition). To provide some context, we aim to establish a Terraform-based stack for deploying the router component. Our plan is to create a customized container image where we can inject our configuration files. Using the latest tag is not suitable for us because we want to have more control over the rollout of new router releases. Do you have any plans to tag or create a GitHub release whenever there are changes in the [libraries/router](https://github.com/kamilkisiela/graphql-hive/tree/main/packages/libraries/router) directory? While using the commit SHA could work, it becomes challenging to track the specific changes made.

**Comment by dotansimha** [comment]
oops, re-opening. I will share an update here soon once the Crate is published :)

**Comment by dotansimha** [comment]
Hi @rcrowe @akoenig 

You can find the Hive plugin in Crates now: https://crates.io/crates/hive-apollo-router-plugin 

Also, check the [Product Update](https://the-guild.dev/graphql/hive/product-updates/2024-11-13-hive-plugin-apollo-router-crate) and [updated docs](https://the-guild.dev/graphql/hive/docs/other-integrations/apollo-router#configuration-1).
